### ISSUE TITLE
Desktop license doesn't allow commercial use.?

### ISSUE THREAD

**Issue by dtanner** [httpie/desktop#117]
The [license](https://github.com/httpie/desktop/blob/master/LICENCE) links to https://httpie.io/terms, 
which contains this for usage:

```
1.2 Limited License

Subject to the terms and conditions of this Agreement, you are hereby granted a non-exclusive, limited, non-transferable, freely revocable license to use the Service for your personal, noncommercial use only and as permitted by the features of the Service. HTTPie reserves all rights not expressly granted herein in the Service and the HTTPie Content (as defined below). HTTPie may terminate this license at any time for any reason or no reason.
```

I read this as "I can't use the desktop app for commercial use", which I'm guessing is not what you intend. Can you clarify this? Thanks.

**Comment by jkbrzt** [comment]
@dtanner Correct, it’s not intentional — everyone is welcome to use the desktop app for commercial use. The terms are being updated, and the “non-commercial” clause will be removed (it slipped in unintentionally by basing our terms on a template).

**Comment by TheFanatr** [comment]
Hi! I, too, have been wondering about the license, because after reading terms page mentioned above, I did not find any information on whether or not personal, commercial, or partial use of the source code is allowed; if I used some tool chain such that the code in this repo could produce an iOS app with the same functionality as the desktop app, could I use it? Currently the terms of the license, to me, imply that this project is source-available, and not open source; clarification of the nature our allowed access to the source code itself, not just the end product, would be, I think, useful. Also, the same document says that company content may be indexed, but not archived, by search engines. does this mean that individuals can archive? Does this also apply to the source code? Does this mean that the internet archive cannot ever archive your website? Just curious about the last one, but as for archival of the source, I do feel that clarification would go some ways towards disambiguating how the terms treat the end product vs the source. Thanks!

**Comment by pbrgr** [comment]
We are currently looking for a good alternative for Postman for various reasons, which we can recommend to our developers without hesitation. We think HTTPie could be a good option. However, the license files do not currently define that commercial use is permitted at all. This would actually prevent us from making this recommendation. Would it be possible to make the license information clear in the short term?

**Comment by CuteistCat** [comment]
WHy dont u just free it like the nondesktop one?

**Comment by jkbrzt** [comment]
✅ Fixed
