### ISSUE TITLE
[Bug]: Hotkeys ctrl+W turned off the app

### ISSUE THREAD

**Issue by ya-makariy** [httpie/desktop#21]
### What happened?

When using the ctrl+W hotkeys to close the selected draft request, the application exited.

### Steps to reproduce?

```Markdown
1. Launch app
2. Open some request's draft
3. Use hotkey ctrl+W
4. App is turned off
```

### What did you expect to happen?

The selected request draft will close

### Platform

Windows

### HTTPie Desktop version

2022.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by timschonborn** [comment]
I would like it if ctrl (cmd) + W closes the current tab/request. Ctrl (Cmd) + Q the app. That's at least how most of the mac apps work (e.g. chrome, vscode). 
I have Ctrl + W in muscle memory for closing tabs and as a result, ended up quitting httpie multiple times instead of just closing the tab. Amazing app though, keep up the great work :)

**Comment by claudiatd** [comment]
I feel you @ya-makariy and @timschonborn ! Soon we'll be working on making an advanced keyboard shortcut system and this issue will be solved by then 💯 I'll keep you posted :)

**Comment by jakubroztocil** [comment]
Thanks for the feedback, everyone! 

We’ve just shipped keyboard shortcuts 👇 

https://httpie.io/blog/changelog-0019

![image](https://user-images.githubusercontent.com/326885/192600005-d0524c44-3316-4c8c-800f-e52785ce56b5.png)
